//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-0f095f89ae15be883"
mykey = "<pemkey here without .pem>"
tags = ["worker_1", "worker_2", "worker_3", "worker_4"]
workerinstancetype = "t2.micro"
masterinstancetype = "t3a.medium"
num = 4
region = "us-east-1"
mysecgr = "ansible-project-207-sec-gr"
user = "user-name"